### PR TITLE
Fix installing gradient library error and add delay

### PR DESCRIPTION
**Pull request by kokomif**
For a temporary solution to not being able to install the gradient library, I added a modification to the gradient library and added a delay to the program for avoid temporary API bans from paperspace.

### CODE REVIEW

**Comment by mrakgr** [comment]
```
because if using pip install gradient will result in an error, a modification is included in this repository so you need to install the library by

pip install -e /path/to/unpacked/repo/gradient-cli

this is just a temporary solution
```

Is there some problem with 'pip install gradient'? Could you go into more detail about what this is supposed to be doing?

Thanks!

**Comment by kokomif** [comment]
sourced from the 
[gradient-cli issue](https://github.com/Paperspace/gradient-cli/issues/397)
Screenshot 2023-12-01 205941


failed to install the gradient library due to broken `PyYAML 5.4.1` and after I tried the solution use `PyYAML 5.3.1` and it turned out to be able to install the gradient library

**Comment by mrakgr** [comment]
Why is a delay necessary? Back when I made the script I opted not to put it in because a single request took seconds as is. Did anything change in the interim?

Don't explain that to me, put it in the readme instead. All the pertinent information should be there.

Explain to the user why a hotfix might be necessary and put that in the readme. Explain what the error is, and link to the issue if necessary.

**Comment by kokomif** [comment]
thank you for your feedback, and apologize for the hurry pull request I will close this pull request.
as a note to overcome the error when installing the gradient library can be by installing PyYAML first
`pip install PyYAML==5.3.*`
then 
```
pip install gradient
pip install plyer
```

and for the addition of delay, I once experienced a temporary ban from paperspace API requests because too many requests maybe 10 minutes did not get a GPU so I could not request APIs temporarily because I was temporarily banned.

**Comment by mrakgr** [comment]
No problem. The issue you've linked here might be useful to anybody trawling through this repo. Hopefully the gradient issue gets fixed soon.

**Pull request closed without merging**
